// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'next_pass';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String LOCK_ANIMATION = 'assets/animations/lock_animation.json';
  static const String BIOMETRIC_ICON = 'assets/icons/Biometric_icon.svg';
  static const String STAR = 'assets/icons/Star.svg';
  static const String CROSS_ICON = 'assets/icons/cross_icon.svg';
  static const String ELLIPSE_ICON = 'assets/icons/ellipse_icon.svg';
  static const String POLYGON_ICON = 'assets/icons/polygon_icon.svg';
  static const String RECTANGLE_ICON = 'assets/icons/rectangle_icon.svg';
  static const String SECOND_LOCK_ICON = 'assets/icons/second_lock_icon.svg';
}
