// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'next_pass';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CROSS_CANCEL_ICON = 'assets/icons/cross_cancel_icon.svg';
}
